languageCode           = "zh-cn"
baseUrl                = 'https://bakacat.netlify.app/'
title                  = '(â˜†-ï½–-) BakaCat'
author                 = 'BakaCat'
theme                  = 'hugo-bearblog'
copyright              = "Copyright Â© 2021, BakaCat"
enableRobotsTXT        = true
enableEmoji            = true

[params]
  description = "Hugo + Bear = :heart:"
  favicon = "images/favicon.svg"
  title = "Bear Ê•â€¢á´¥â€¢Ê”"
  twitter_username = "bakacatuwu"
  search_engine = true

[indexes]
  category = "category"
  tag = "tag"

[menu]

  [[menu.main]]
    identifier = "sex"
    name = "é»„è‰²åºŸæ–™ğŸ§¸"
    url = "/sex/"
    weight = 20

  [[menu.main]]
    identifier = "blog"
    name = "ä¸€äº›é—²è¯ğŸŒ "
    url = "/blog/"
    weight = 30

  [[menu.main]]
    identifier = "useful"
    name = "æœ‰ç”¨çš„ğŸŒŒ"
    url = "/useful/"
    weight = 40

  [[menu.main]]
    name = "å…³äºæˆ‘ğŸ–ğŸ»"
    url = "/about/"
    weight = 50